/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_JNISample */

#ifndef _Included_com_example_jni_JNISample
#define _Included_com_example_jni_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_JNISample
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jni_JNISample_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
